#!/bin/bash

pid_file="/tmp/pid_file"

case "$1" in
    "kill" )
	kill -s SIGTERM $( cat "$pid_file")
	;;
    "is-up")
	kill -0 $( cat "$pid_file" ) 2&> /dev/null && echo "runnung" || echo "not runnuing"
	;;
    "rexec")
	kill -s SIGHUP $( cat "$pid_file" )
	;;
    "up")
	$PWD/run --dump_config --log_err $PWD/run-err.log --log_out $PWD/run-dbg.log --ring_prog $PWD/ringer
	;;
    * )
	echo "Unknown action $1"
	;;
esac

