#!/bin/bash

if [ ! $UID -eq '0' ]; then
    echo 'Need root privileges'
    exit 1;
fi
    

pid_file="/tmp/pid_file"
logdir="/var/log/bell"

case "$1" in
    "kill" )
	kill -s SIGTERM $( cat "$pid_file")
	;;
    "is-up")
	kill -0 $( cat "$pid_file" ) 2&> /dev/null && echo "runnung" || echo "not runnuing"
	;;
    "rexec")
	kill -s SIGHUP $( cat "$pid_file" )
	;;
    "up")
	/sbin/run --dump_config  --log_err $logdir/run-err.log --log_out $logdir/run-dbg.log \
	    --ring_prog /sbin/ringer --pid_file $pid_file
	;;
    * )
	echo "Unknown action $1"
	;;
esac

