PATH=/var/www/html

.PHONY: install
install:
	/bin/cp error.php style2.css daemon_op.php mysql_op.php site.php test.php print_funcs.php $(PATH)
	/bin/cp pages/* $(PATH)/pages
	/bin/cp img/*   $(PATH)/img
